### ISSUE TITLE
Missing padas package

### ISSUE THREAD

**Issue by ChHarding** [Pinanana/FoneFridge_HCI584#1]
- pandas should have been installed as part of Anaconda
- make sure you're running the same python interpreter version (3.8.5?) in VSCode as you've installed via Anaconda. The interpreters is shown in the lower right (on the info line at the bottom), click it to change to a different interpreter
- Or, bring up a terminal and type pip list  - this lists all installed packages. If you don't see it there, type pip install pandas to install it

**Comment by Pinanana** [comment]
It worked! Once I switched from 3.7.3 to 3.9.1 I could load the modules. Thank you!
